import { Inter } from "next/font/google";
import { Provider } from "@/context/store";
import Nav from "@/components/nav";
import "../style/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Digital Agency Indonesia | Web & Mobile App Development Consultant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://suitmedia.com/favicon.png"
          type="image/png"
          sizes="32x32"
        />
      </head>
      <body className={inter.className}>
        <Provider>
          <Nav></Nav>
          {children}
        </Provider>
      </body>
    </html>
  );
}
